# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airtone < Formula
  desc "Stream your Mac's system audio to your phone in sync — gapless, no app required."
  homepage "https://github.com/sait-turanalp/airtone"
  version "0.3.2"
  license "MIT"

  depends_on "ffmpeg"
  depends_on "snapcast"
  depends_on "sox"
  depends_on "switchaudio-osx"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/sait-turanalp/airtone/releases/download/v0.3.2/airtone_0.3.2_darwin_amd64.tar.gz"
    sha256 "edf0b0f9ca10d7c4d83904cd0945c98a7827a4daec456ce01734327c805b3b31"

    define_method(:install) do
      bin.install "airtone"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/sait-turanalp/airtone/releases/download/v0.3.2/airtone_0.3.2_darwin_arm64.tar.gz"
    sha256 "c0f52e4a185049e54d0f7c7d4f9644be20e9d925cba737014f9e880600d6cbea"

    define_method(:install) do
      bin.install "airtone"
    end
  end

  def caveats
    <<~EOS
      AirTone also needs the BlackHole 2ch audio driver, which cannot be a
      formula dependency. Install it once (needs admin + a reboot):

        brew install --cask blackhole-2ch

      Then run:  airtone setup
    EOS
  end
end
