# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airtone < Formula
  desc "Stream your Mac's system audio to your phone in sync — gapless, no app required."
  homepage "https://github.com/sait-turanalp/airtone"
  version "0.1.0"
  license "MIT"

  depends_on "snapcast"
  depends_on "sox"
  depends_on "switchaudio-osx"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/sait-turanalp/airtone/releases/download/v0.1.0/airtone_0.1.0_darwin_amd64.tar.gz"
    sha256 "03558d7efe52c88c946908ee196c503a825a136f57637cb3e9637b297428b222"

    define_method(:install) do
      bin.install "airtone"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/sait-turanalp/airtone/releases/download/v0.1.0/airtone_0.1.0_darwin_arm64.tar.gz"
    sha256 "90766c6218de6a7042df0cf508be0db02c1dde8f8de1fb91c6c74cc79de6ebc0"

    define_method(:install) do
      bin.install "airtone"
    end
  end

  def caveats
    <<~EOS
      AirTone also needs the BlackHole 2ch audio driver, which cannot be a
      formula dependency. Install it once (needs admin + a reboot):

        brew install --cask blackhole-2ch

      Then run:  airtone setup
    EOS
  end
end
