# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airtone < Formula
  desc "Stream your Mac's system audio to your phone in sync — gapless, no app required."
  homepage "https://github.com/sait-turanalp/airtone"
  version "0.2.0"
  license "MIT"

  depends_on "ffmpeg"
  depends_on "snapcast"
  depends_on "sox"
  depends_on "switchaudio-osx"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/sait-turanalp/airtone/releases/download/v0.2.0/airtone_0.2.0_darwin_amd64.tar.gz"
    sha256 "55aedb7b0193014230e3f816905af3d15a39602fe1cce54f2af45fc708ad262e"

    define_method(:install) do
      bin.install "airtone"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/sait-turanalp/airtone/releases/download/v0.2.0/airtone_0.2.0_darwin_arm64.tar.gz"
    sha256 "0e6775876335e46681c5a98891dcf5ad5fd6ee56410b1bf1750fd5a5b3ec3dc8"

    define_method(:install) do
      bin.install "airtone"
    end
  end

  def caveats
    <<~EOS
      AirTone also needs the BlackHole 2ch audio driver, which cannot be a
      formula dependency. Install it once (needs admin + a reboot):

        brew install --cask blackhole-2ch

      Then run:  airtone setup
    EOS
  end
end
